<a href="https://colab.research.google.com/github/Lekanville/Text-Line-Handwriting-Classification/blob/main/CNN2_Handwriting_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from numpy import save
from numpy import load
import matplotlib.pyplot as plt

In [ ]:
from numpy import save
from numpy import load

In [ ]:
data = load('drive/MyDrive/Colab_Notebooks/Handwriting_Classification/data.npy')

In [ ]:
labels = load('drive/MyDrive/Colab_Notebooks/Handwriting_Classification/labels.npy')

In [ ]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import BatchNormalization
from keras.layers import Conv2D
from keras.layers import Activation
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import Input
from keras.layers import MaxPooling2D
from keras.models import Model
from keras.optimizers import RMSprop
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = data
X.shape

(18820, 32, 256)

In [ ]:
X = X.reshape((-1,32,256,1))
X.shape

(18820, 32, 256, 1)

In [ ]:
y = []
for i in labels:
    if i == 1:
        ts = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    elif i ==2:
        ts = [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    elif i ==3:
        ts = [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    elif i ==4:
        ts = [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    elif i ==5:
        ts = [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    elif i ==6:
        ts = [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
    elif i ==7:
        ts = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    elif i ==8:
        ts = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
    elif i ==9:
        ts = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
    elif i ==10:
        ts = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    y.append(ts)
y = np.asarray(y, dtype=np.float32)
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(16938, 32, 256, 1)
(1882, 32, 256, 1)


In [ ]:
print(y_train.shape)
print(y_test.shape)

(16938, 10)
(1882, 10)


In [ ]:
model = Sequential()

model.add(Conv2D(16,(5,5),padding='same',input_shape = (32, 256, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding = 'same'))
#model.add(Dropout(0.4))

model.add(Conv2D(32,(5,5),padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding = 'same'))
#model.add(Dropout(0.6))

model.add(Conv2D(64,(5,5),padding='same'))
model.add(Activation('relu'))
#model.add(Dropout(0.8))

model.add(Flatten())
model.add(Dense(10))
model.add(Activation('softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 256, 16)       416       
_________________________________________________________________
activation (Activation)      (None, 32, 256, 16)       0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 16, 128, 16)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 16, 128, 32)       12832     
_________________________________________________________________
activation_1 (Activation)    (None, 16, 128, 32)       0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 64, 32)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 64, 64)         5

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
                   
model.fit(X_train, y_train, epochs=300, batch_size=100, verbose=100)
history = model.fit(X_train,y_train,steps_per_epoch = int(len(X_train)/batch_size),epochs=epochs)
history

Epoch 1/300
Epoch 2/300
Epoch 3/300
Epoch 4/300
Epoch 5/300
Epoch 6/300
Epoch 7/300
Epoch 8/300
Epoch 9/300
Epoch 10/300
Epoch 11/300
Epoch 12/300
Epoch 13/300
Epoch 14/300
Epoch 15/300
Epoch 16/300
Epoch 17/300
Epoch 18/300
Epoch 19/300
Epoch 20/300
Epoch 21/300
Epoch 22/300
Epoch 23/300
Epoch 24/300
Epoch 25/300
Epoch 26/300
Epoch 27/300
Epoch 28/300
Epoch 29/300
Epoch 30/300
Epoch 31/300
Epoch 32/300
Epoch 33/300
Epoch 34/300
Epoch 35/300
Epoch 36/300
Epoch 37/300
Epoch 38/300
Epoch 39/300
Epoch 40/300
Epoch 41/300
Epoch 42/300
Epoch 43/300
Epoch 44/300
Epoch 45/300
Epoch 46/300
Epoch 47/300
Epoch 48/300
Epoch 49/300
Epoch 50/300
Epoch 51/300
Epoch 52/300
Epoch 53/300
Epoch 54/300
Epoch 55/300
Epoch 56/300
Epoch 57/300
Epoch 58/300
Epoch 59/300
Epoch 60/300
Epoch 61/300
Epoch 62/300
Epoch 63/300
Epoch 64/300
Epoch 65/300
Epoch 66/300
Epoch 67/300
Epoch 68/300
Epoch 69/300
Epoch 70/300
Epoch 71/300
Epoch 72/300
Epoch 73/300
Epoch 74/300
Epoch 75/300
Epoch 76/300
Epoch 77/300
Epoch 78

In [ ]:
y_pred = np.argmax(model.predict(X_test), axis=-1)

In [ ]:
print(confusion_matrix(np.argmax(y_test, axis = 1), y_pred))
print('\n')
print(classification_report(np.argmax(y_test, axis = 1), y_pred))

[[ 96  13   6   1   3   1   6   0   1   0]
 [  9 196   0   1   5   1   2   1   0   1]
 [  1   0 201   1   0   0   3   2   1   1]
 [  0   1   2 172   0   0   5   1   2   6]
 [  0   1   0   0 182   2   1   0   0   1]
 [  0   5   0   0   3 138   3   2   0   0]
 [  2   2   4   4   0   0 189  20   3   0]
 [  0   0   0   0   0   2  11 187   0   3]
 [  1   0   0   0   0   0   5   1 166   9]
 [  1   0   1   3   0   0   4   1  11 172]]


              precision    recall  f1-score   support

           0       0.87      0.76      0.81       127
           1       0.90      0.91      0.90       216
           2       0.94      0.96      0.95       210
           3       0.95      0.91      0.93       189
           4       0.94      0.97      0.96       187
           5       0.96      0.91      0.94       151
           6       0.83      0.84      0.83       224
           7       0.87      0.92      0.89       203
           8       0.90      0.91      0.91       182
           9       0.89   

In [ ]:
#Using othet algorithms
model_feat = Model(inputs=model.input,outputs=model.output)
feat_train = model_feat.predict(X_train)
feat_test = model_feat.predict(X_test)

SVM

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [ ]:
svm_model = SVC()
svm_model.fit(feat_train,np.argmax(y_train,axis=1))

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
svm_predictions = svm_model.predict(feat_test)

In [ ]:
svm_predictions

array([0, 8, 8, ..., 4, 6, 7])

In [ ]:
print(confusion_matrix(np.argmax(y_test, axis = 1), svm_predictions))
print('\n')
print(classification_report(np.argmax(y_test, axis = 1), svm_predictions))

[[ 96  13   6   1   3   1   6   0   1   0]
 [  9 196   0   1   5   1   2   1   0   1]
 [  3   0 201   0   0   0   3   2   0   1]
 [  0   1   2 172   0   0   5   1   2   6]
 [  0   1   0   0 182   2   1   0   0   1]
 [  0   5   0   0   3 138   3   2   0   0]
 [  2   2   4   4   0   0 189  20   3   0]
 [  0   0   0   0   0   2  11 187   0   3]
 [  1   0   0   0   0   0   5   1 166   9]
 [  1   0   1   3   0   0   4   1  11 172]]


              precision    recall  f1-score   support

           0       0.86      0.76      0.80       127
           1       0.90      0.91      0.90       216
           2       0.94      0.96      0.95       210
           3       0.95      0.91      0.93       189
           4       0.94      0.97      0.96       187
           5       0.96      0.91      0.94       151
           6       0.83      0.84      0.83       224
           7       0.87      0.92      0.89       203
           8       0.91      0.91      0.91       182
           9       0.89   

In [ ]:
svm_model.score(feat_test,np.argmax(y_test,axis=1))

0.9027630180658873

Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(feat_train,np.argmax(y_train,axis=1))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
dt_predictions = dt.predict(X_test)

ValueError: ignored

In [ ]:
print(confusion_matrix(np.argmax(y_test, axis = 1), dt_predictions))
print('\n')
print(classification_report(np.argmax(y_test, axis = 1), dt_predictions))

[[ 97  13   5   1   3   1   6   0   1   0]
 [  9 196   0   1   5   1   2   1   0   1]
 [  2   0 201   0   0   0   3   3   0   1]
 [  0   1   2 172   0   0   5   1   2   6]
 [  0   1   0   0 182   2   1   0   0   1]
 [  0   5   0   0   3 138   3   2   0   0]
 [  1   2   4   4   0   0 186  24   3   0]
 [  0   0   0   0   0   2   9 190   0   2]
 [  1   0   0   0   0   0   5   2 165   9]
 [  1   0   1   3   0   0   4   1  11 172]]


              precision    recall  f1-score   support

           0       0.87      0.76      0.82       127
           1       0.90      0.91      0.90       216
           2       0.94      0.96      0.95       210
           3       0.95      0.91      0.93       189
           4       0.94      0.97      0.96       187
           5       0.96      0.91      0.94       151
           6       0.83      0.83      0.83       224
           7       0.85      0.94      0.89       203
           8       0.91      0.91      0.91       182
           9       0.90   

In [ ]:
dt.score(feat_test,np.argmax(y_test,axis=1))

0.9027630180658873